#############################################################################
# Makefile for building: kqoauth
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Nov 30 17:19:41 2010
# Project:  kqoauth.pro
# Template: subdirs
# Command: /usr/local/Trolltech/QtEmbedded-4.6.2/bin/qmake -unix -o Makefile kqoauth.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/Trolltech/QtEmbedded-4.6.2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src \
		sub-examples \
		sub-tests

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/reilly/kqoauth/src/src.pro -unix -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/reilly/kqoauth/src/src.pro -unix -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
examples/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) examples/ || $(MKDIR) examples/ 
	cd examples/ && $(QMAKE) /home/reilly/kqoauth/examples/examples.pro -unix -o $(MAKEFILE)
sub-examples-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) examples/ || $(MKDIR) examples/ 
	cd examples/ && $(QMAKE) /home/reilly/kqoauth/examples/examples.pro -unix -o $(MAKEFILE)
sub-examples: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE)
sub-examples-make_default-ordered: examples/$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-make_default: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-make_first-ordered: examples/$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-make_first: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-all-ordered: examples/$(MAKEFILE) sub-src-all-ordered  FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-all: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-clean-ordered: examples/$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-clean: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-distclean-ordered: examples/$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-distclean: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-install_subtargets-ordered: examples/$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-install_subtargets: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-uninstall_subtargets-ordered: examples/$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-examples-uninstall_subtargets: examples/$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) uninstall
tests/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tests/ || $(MKDIR) tests/ 
	cd tests/ && $(QMAKE) /home/reilly/kqoauth/tests/tests.pro -unix -o $(MAKEFILE)
sub-tests-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tests/ || $(MKDIR) tests/ 
	cd tests/ && $(QMAKE) /home/reilly/kqoauth/tests/tests.pro -unix -o $(MAKEFILE)
sub-tests: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE)
sub-tests-make_default-ordered: tests/$(MAKEFILE) sub-examples-make_default-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) 
sub-tests-make_default: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) 
sub-tests-make_first-ordered: tests/$(MAKEFILE) sub-examples-make_first-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) first
sub-tests-make_first: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) first
sub-tests-all-ordered: tests/$(MAKEFILE) sub-examples-all-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) all
sub-tests-all: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) all
sub-tests-clean-ordered: tests/$(MAKEFILE) sub-examples-clean-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) clean
sub-tests-clean: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) clean
sub-tests-distclean-ordered: tests/$(MAKEFILE) sub-examples-distclean-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tests-distclean: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tests-install_subtargets-ordered: tests/$(MAKEFILE) sub-examples-install_subtargets-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) install
sub-tests-install_subtargets: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) install
sub-tests-uninstall_subtargets-ordered: tests/$(MAKEFILE) sub-examples-uninstall_subtargets-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-tests-uninstall_subtargets: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: kqoauth.pro  /usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/qws/linux-x86-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/debug.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile kqoauth.pro
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/common/g++.conf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/debug.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.6.2/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile kqoauth.pro

qmake_all: sub-src-qmake_all sub-examples-qmake_all sub-tests-qmake_all FORCE

make_default: sub-src-make_default-ordered sub-examples-make_default-ordered sub-tests-make_default-ordered FORCE
make_first: sub-src-make_first-ordered sub-examples-make_first-ordered sub-tests-make_first-ordered FORCE
all: sub-src-all-ordered sub-examples-all-ordered sub-tests-all-ordered FORCE
clean: sub-src-clean-ordered sub-examples-clean-ordered sub-tests-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-examples-distclean-ordered sub-tests-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-examples-install_subtargets-ordered sub-tests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-examples-uninstall_subtargets-ordered sub-tests-uninstall_subtargets-ordered FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

